### ISSUE TITLE
Failing test cases in inout branch (Linear.cs)

### ISSUE THREAD

**Issue by Chris-Hawblitzel** [secure-foundations/dafny#14]
Linear.cs is crashing on the following tests in the inout branch:

Test/allocated1/dafny0/DirtyLoops.dfy
Test/dafny0/DirtyLoops.dfy
Test/patterns/PatternMatchingErrors.dfy
Test/patterns/PatternMatching.dfy

Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.BlockStmt' to type 'Microsoft.Dafny.MatchStmt'.
   at Microsoft.Dafny.Linear.Visit.<AllStatementLists>d__1.MoveNext() in Source/Dafny/Linear.cs:line 105

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.Linear.Visit.<AllStatementLists>d__1.MoveNext() in Source/Dafny/Linear.cs:line 112

**Comment by utaal** [comment]
On the `inout` branch, `ac317728b46ec9138812aa855608550ad2ef14fa` fixes `Test/allocated1/dafny0/DirtyLoops.dfy` and `f4920b6dee00a46fdb65c044de5fe230c9eda9d3` ought to fix `Test/patterns/PatternMatchingErrors.dfy` and `Test/patterns/PatternMatching.dfy` but the tests still don't pass.

**Comment by parno** [comment]
@utaal FWIW, these tests all pass on `inout-merge`, so perhaps we can close this issue?
