### ISSUE TITLE
linear inout parameter causing crash in dafny

### ISSUE THREAD

**Issue by jialin-li** [secure-foundations/dafny#21]
For methods with linear inout arguments, if the first parameter is not a linear inout argument, dafny crashes.

Here are some examples:
```
datatype A = A(a: int)
linear datatype B = B(b: int)

// crashes
method SeqThenLinear(s: seq<A>, linear inout b: B)
{}

// fine
method LinearThenSeq(linear inout b: B, s: seq<A>)
{}

// crashes
method SharedThenLinear(shared b1: B, linear inout b2: B)
{}

// fine
method LinearThenShared(linear inout b1: B, shared b2: B)
{}

// fine
method InoutInout(linear inout b1: B, linear inout b2: B)
```

This happens for recent commits on `betr` branch, [here](https://github.com/secure-foundations/dafny/commit/e61278bead64d5a715ac9400ff7f721301ce8b53) is an example commit.

**Comment by utaal** [comment]
Fixed in `betr`, I think (`betr` seems be in a somewhat broken state currently).
