### ISSUE TITLE
glinear datatypes

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#22]
We need support for both:

 * linear datatypes that can hold `glinea`r fields
 * `glinear` datatypes (which can only hold `glinear` and ghost fields, no normal linear fields)

A glinear datatype with a non-ghost field wouldn't make any sense.

Right now the situation appears to be:

 * Datatypes can have `glinear` fields
 * You can't put `glinear` before a `datatype`

However, you _can_ have a `glinear` var to a `linear` datatype, which lets you build weird stuff like this:  

```
linear datatype Foo =
    Foo(
      linear y: int,
      glinear x: int)

method m(glinear foo: Foo)
returns (
      linear y: int,
      glinear x: int)
{
  glinear var Foo(y', x') := foo;
  y := y';
  x := x;
}
```

This verifies, even though, we're conjuring a `linear y` out of nowhere. Admittedly, this might not _technically_ be unsound (you can't create a `glinear foo` in the first place?) but it probably shouldn't be allowed.

**Comment by Chris-Hawblitzel** [comment]
I just added glinear datatypes.
