### ISSUE TITLE
cpp template errors for templated datatype methods

### ISSUE THREAD

**Issue by jialin-li** [secure-foundations/dafny#25]
The datatype methods of a templated datatype `Foo<A>` cause the dafny to cpp compiler emits too many `template<typename A>` that results in cpp compilation errors. This happens only for datatype methods, function methods and methods outside of the datatype are both ok. This can be seen when using the latest [betr](https://github.com/secure-foundations/dafny/commit/77ca21eeb22ab9b0c6c8b51a05861ddcce5a4c63) branch.

Example:
```
module Test {

  datatype Foo<A> = Foo(a: A) {

    // ok
    function method AllocFun(a: A) : (f: Foo<A>)
    {
       Foo(a)
    }
    
    // problematic when being compiled
    static method Alloc(a: A) returns (f: Foo<A>) 
    {
      f := Foo(a);
    }
  }
 
  // ok 
  method Outside<A>(a: A) returns (f: Foo<A>) 
  {
    f := Foo(a);
  }
}
```

Dafny command: `tools/local-dafny.sh  /compile:0 /noVerify /spillTargetCode:3 /countVerificationErrors:0 /out:test.cpp /compileTarget:cpp example.i.dfy /trace`

Generated header file
`````
template <typename A>
struct Foo {
    A a;
    Foo(A a) : a (a) {}
    Foo();
    Foo* operator->() { return this; }
    friend bool operator==<A>(const Foo &left, const Foo &right);
    friend bool operator!=(const Foo &left, const Foo &right) { return !(left == right); } 
   =======> template <typename A> // shadow template error
    static Test_Compile::Foo <A>  Alloc(A a);
  };
`````

Generated cpp file:
`````
namespace Test_Compile  {
 ===> template <typename A> // two templates generated for Alloc
  template <typename A>
  Test_Compile::Foo <A>  Foo<A>::Alloc(A a)
  {
    Test_Compile::Foo <A>  f = Test_Compile::Foo<A>();
    f = Test_Compile::Foo<A>(a);
    return f;
  }

  template <typename __A>
  Test_Compile::Foo <__A>  __default::Outside(__A a) // ok
  {
    Test_Compile::Foo <__A>  f = Test_Compile::Foo<__A>();
    f = Test_Compile::Foo<__A>(a);
    return f;
  }
}
`````

Command for compiling the generated cpp file `clang++ -stdlib=libc++ -I .dafny/dafny//Binaries/ -I framework/ -I build/ -std=c++17 -march=native test.cpp`

**Comment by parno** [comment]
I think 66f6b69 should fix this.  Can you check on the larger version?

**Comment by jialin-li** [comment]
The above commit fixes the issue :).
