### ISSUE TITLE
inout update not reflected in the generated cpp code

### ISSUE THREAD

**Issue by jialin-li** [secure-foundations/dafny#27]
Currently when we use `inout` to update a struct's field, the generated code doesn't actually overwrite the field, but a stack copy of the field. To fix this, we can add another getter function that returns the reference. When we use `inout` keyword, we invoke the reference getter function instead of the value getter function.

This is an example:
`````
#include <iostream>

struct Bar {
    int a;
    Bar& operator=(const Bar other) {
      a = other.a;
      return *this;
    }
};

struct Foo {
    struct Bar b; 
  
    // current code
    struct Bar get() {
      return b; 
    }

   // proposed option
    struct Bar& getref() {
      return b; 
    }
};

int main() {
    struct Bar b;
    struct Bar b2;
    struct Foo f;

    b.a = 2;
    b2.a = 5;
    f.b = b;

    // f.get() = b2; // b2 overwrites the returned copy of f.b, no change is done on f.b
    f.getref() = b2; // b2 overwrites the reference of f.b, change is reflected

    std::cout<< f.b.a << "\n";
}
`````

**Comment by parno** [comment]
I think this might be addressed by the fix that Jack is working on for https://github.com/secure-foundations/dafny/issues/9
