### ISSUE TITLE
dafny should error on malformed module import

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#31]
Suppose I've got

```dafny
abstract module SSM {  }
abstract module PCM {  }

module Tokens(pcm: PCM) { } 

module SSM_PCM(ssm: SSM) refines PCM {  }

module SSMTokens(ssm: SSM) {
  import Tokens = Tokens(SSM_PCM)
}
```

I expect the import to error - SSM_PCM is a functor, but I haven't given it any argument here. The correct import should be `Tokens(SSM_PCM(ssm))` instead.

Current behavior is Dafny silently accepts this even though it's basically meaningless. Leads to a headache of verification failures later that are hard to identify.

**Comment by parno** [comment]
Interesting.  There are some checks for missing functor arguments, but apparently we're not hitting them here.  I'll look into it.
