### ISSUE TITLE
better error messages for type resolution errors

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#32]
Errors like this have always been kind of annoying:
```
function expects BaseTokens.Token, got Token
```
This is even more confusing now in the Module System. It would be nice if these error message could fully qualify the type names, and ideally expanding out the entire functor application instead of just using aliases

**Comment by parno** [comment]
Do you have an example repro and an example of what you'd like to see?

**Comment by tjhance** [comment]
hm, sure. So in this for example,

```
abstract module TotalOrder {
  type V

  predicate le(a: V, b: V)

  lemma le_self(a: V)
  ensures le(a, a)

  lemma le_transitive(a: V, b: V, c: V)
  ensures le(a, b) && le(b, c) ==> le(a, c)
}

abstract module TotalOrderImpl(to: TotalOrder) {
  method compute_le(x: to.V, y: to.V)
  returns (b: bool)
  ensures b == to.le(x, y)
}

module IntTotalOrder refines TotalOrder {
  type V = int
  predicate le(a: V, b: V) { a <= b }
  lemma le_self(a: V) { }
  lemma le_transitive(a: V, b: V, c: V) { }
}

module BoolTotalOrder refines TotalOrder {
  type V = bool
  predicate le(a: V, b: V) { !a || b }
  lemma le_self(a: V) { }
  lemma le_transitive(a: V, b: V, c: V) { }
}

module X {
  import ZZZ = IntTotalOrder
  import BoolTotalOrder

  predicate f(x: ZZZ.V) {
    BoolTotalOrder.le(x, x)
  }
}
```

the error message is,

```
function expects V, got ZZZ.V
```

Two problems here. (i) the first `V` isn't qualified at all and (ii) the `ZZZ.V` uses the module alias name.

It'd be way better if it said
```
function expects BoolTotalOrder.V, got IntTotalOrder.V
```

Or possibly it could give both,

```
function expects V (BoolTotalOrder.V), got ZZZ.V (IntTotalOrder.V)
```

And of course, when functors come into the game, I'd expect that the "fully qualified names" would sometimes have functor applications in them, or be written in terms of module parameters.

**Comment by parno** [comment]
I just pushed 8a2d7a5, which enables additional type detail (at least for some error messages) if you run with the `/titrace` (type-inference trace) flag.  The flag spews a bunch of other data, but it eventually also produces an error message along with the fully-qualified name.  I think that will include some possibly useful information on the provenance of functor outputs as well, but I haven't tested it.
