### ISSUE TITLE
another "not allowed to use an abstract module" error

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#37]
```dafny
abstract module Rw {

}

module RwTokens(rw: Rw) {
  datatype Token = Tok  
}

abstract module StoredTypeModule {

}

module RwLock(stm: StoredTypeModule) refines Rw {

}

module RwLockTokens(stm: StoredTypeModule) {
  import rwlock = RwLock(stm)
  import T = RwTokens(RwLock(stm))

  type Token = T.Token
}

module RwLockImpl(stm: StoredTypeModule) {
  import rwlock = RwLock(stm)
  import T = RwLockTokens(stm)

  type Token = T.Token
}
```

```
(21,15): Error: a compiled module is not allowed to use an abstract module (T)
(21,15): Error: a compiled module is not allowed to use an abstract module (T)
```

**Comment by parno** [comment]
Is this a bug?  In this case, `StoredTypeModule` is an abstract module.  You haven't yet concretized it.  Are you arguing that `stm` should be considered concrete, because it's a functor argument, even though it's been given an abstract type?

**Comment by tjhance** [comment]
yes, exactly

(Also note that this is the same code as https://github.com/secure-foundations/dafny/issues/36 with only the `type` lines added.)

**Comment by parno** [comment]
This example should be working now.  Whole system probably needs a more thorough overhaul, however.
