### ISSUE TITLE
two module params of the same base don't type-check correctly

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#38]
```
abstract module X {
  type T
}

module M(x1: X, x2: X) {
  predicate f(a: x1.T)

  lemma m(b: x2.T)
  requires f(b)
}
```

This passes type-checking; I would expect it to fail with an error like `function expects x1.T, got x2.T`

**Comment by parno** [comment]
I think you'll see an error eventually when you try to apply `M`, in particular, if you apply `M` to two different modules.  If you apply it to the same module twice, it should go through.

**Comment by tjhance** [comment]
that's true. I guess one could argue it's a feature, but I think it's weird that a functor would typecheck but then fail to typecheck when instantiated

**Comment by parno** [comment]
I think the changes necessary to treat this as an error would be likely to break other parts of the system (or require deep changes to Dafny's type checker), so for now, I'm inclined to think of this as a feature.
