### ISSUE TITLE
namespace module names are not fully expanded

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#52]
```dafny
abstract module NRIfc { }

module ContentsTypeMod {
}

module NodeReplica(nrifc: NRIfc) refines ContentsTypeMod { }

module RwLockImpl(contentsTypeMod: ContentsTypeMod) {
}

module Impl(nrifc: NRIfc) {
  import opened NodeReplicaApplied = NodeReplica(nrifc)
  import opened RwLockImpl(NodeReplicaApplied)
}

module ConcreteNrifc2 refines NRIfc { }
module ConcreteNrifc1 refines NRIfc { }

import X = Impl(ConcreteNrifc1)
import Y = Impl(ConcreteNrifc2)
```

This creates some namespaces with `NodeReplicaApplied` in them, e.g., `RwLockImpl_ON_NodeReplicaApplied__Compile`.

But `NodeReplicaApplied` ought to be expanded out to something like `NodeReplica_ON_ConcreteNrifc1`
or `NodeReplica_ON_ConcreteNrifc2`.

This example illustrates a potential problem that arises from this bug: there should be two different namespaces,
`RwLockImpl_ON_NodeReplica_ON_ConcreteNrifc1__Compile` and
`RwLockImpl_ON_NodeReplica_ON_ConcreteNrifc2__Compile`. But instead both are named
`RwLockImpl_ON_NodeReplicaApplied__Compile`.

**Comment by parno** [comment]
Should be fixed by 73023377
